//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Input/BubbleControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @BubbleControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @BubbleControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""BubbleControls"",
    ""maps"": [
        {
            ""name"": ""BFM_Default"",
            ""id"": ""ef09d66a-ba21-4dd4-aa0d-f8306dae4a57"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""4d34b4ea-e8f9-4dec-a2f6-3946cf65bf62"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Menu/Pause"",
                    ""type"": ""Button"",
                    ""id"": ""f7a843de-ddd0-4eb0-abab-d1a0e379e183"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""ab644882-d1a4-450f-82d6-c07b97da7351"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""c6438e2a-7bdf-42a0-a13a-ede0b2d095b2"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""5924ec11-9324-43bc-93e2-94595c5c4c27"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKey"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""b18fd6a4-a813-45a9-9619-092190630864"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKey"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""3fbf0399-8729-4af9-9dec-4ef4f98bc451"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKey"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""9fdb71dd-eafe-43c3-a5c3-54c0fba52b32"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""left"",
                    ""id"": ""865e4543-71f5-421a-bce9-8fd6fa7d9af4"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKey"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""ad6728c8-40cb-4883-8ccb-41b0c6cb284b"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKey"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""cd714294-2737-4bba-a858-307a2f98cb84"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKey"",
                    ""action"": ""Menu/Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6960b30d-d5da-4c3f-a752-7bb13f58aebf"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseKey"",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""MouseKey"",
            ""bindingGroup"": ""MouseKey"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // BFM_Default
        m_BFM_Default = asset.FindActionMap("BFM_Default", throwIfNotFound: true);
        m_BFM_Default_Movement = m_BFM_Default.FindAction("Movement", throwIfNotFound: true);
        m_BFM_Default_MenuPause = m_BFM_Default.FindAction("Menu/Pause", throwIfNotFound: true);
        m_BFM_Default_Interact = m_BFM_Default.FindAction("Interact", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // BFM_Default
    private readonly InputActionMap m_BFM_Default;
    private List<IBFM_DefaultActions> m_BFM_DefaultActionsCallbackInterfaces = new List<IBFM_DefaultActions>();
    private readonly InputAction m_BFM_Default_Movement;
    private readonly InputAction m_BFM_Default_MenuPause;
    private readonly InputAction m_BFM_Default_Interact;
    public struct BFM_DefaultActions
    {
        private @BubbleControls m_Wrapper;
        public BFM_DefaultActions(@BubbleControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_BFM_Default_Movement;
        public InputAction @MenuPause => m_Wrapper.m_BFM_Default_MenuPause;
        public InputAction @Interact => m_Wrapper.m_BFM_Default_Interact;
        public InputActionMap Get() { return m_Wrapper.m_BFM_Default; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BFM_DefaultActions set) { return set.Get(); }
        public void AddCallbacks(IBFM_DefaultActions instance)
        {
            if (instance == null || m_Wrapper.m_BFM_DefaultActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_BFM_DefaultActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @MenuPause.started += instance.OnMenuPause;
            @MenuPause.performed += instance.OnMenuPause;
            @MenuPause.canceled += instance.OnMenuPause;
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
        }

        private void UnregisterCallbacks(IBFM_DefaultActions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @MenuPause.started -= instance.OnMenuPause;
            @MenuPause.performed -= instance.OnMenuPause;
            @MenuPause.canceled -= instance.OnMenuPause;
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
        }

        public void RemoveCallbacks(IBFM_DefaultActions instance)
        {
            if (m_Wrapper.m_BFM_DefaultActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IBFM_DefaultActions instance)
        {
            foreach (var item in m_Wrapper.m_BFM_DefaultActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_BFM_DefaultActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public BFM_DefaultActions @BFM_Default => new BFM_DefaultActions(this);
    private int m_MouseKeySchemeIndex = -1;
    public InputControlScheme MouseKeyScheme
    {
        get
        {
            if (m_MouseKeySchemeIndex == -1) m_MouseKeySchemeIndex = asset.FindControlSchemeIndex("MouseKey");
            return asset.controlSchemes[m_MouseKeySchemeIndex];
        }
    }
    public interface IBFM_DefaultActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnMenuPause(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
    }
}
